# TownyWars 1.3 configuration file

# TRANSLATIONS (%s is a placeholder for version, name etc.)

#Info
msg-compatible: "&f[&aTowny&6Wars&f] &aCompatible with current Towny version"
msg-nocompatible: "&f[&aTowny&6Wars&f] &cWasn't tested with Towny %s"
msg-warin1: "&bWar &c%s &binfo:"
msg-warin2: "&bSide &6%s &btowns: &e"
msg-warin3: "&aPoints: &b%s &7(%k) &fVS &b%j &7(%y)"
msg-peace: "&cThat town hasn't war!"

#Wars

#Set "2" for town and global announce, "1" for only town and "0" to no announce.
public-announce-neutral: 2 # "3" option is only command sender (only in neutrals)
public-announce-warstart: 2
public-announce-warend: 2

price-declare: 200.0
price-neutral: 200.0
create-neutral: true

# Type of war end. Available: "delete" for delete loser town, "prize" for pay money to winner, "steal" for steal bank from loser town
lose-action: "delete"
prize: 200.0

# Delete looser town if balance =< 1
delete-if-cant-steal: true

# Only delete looser town without adding its chunks to winner
only-town-delete: false

# The mayor of the city under attack must be online
mayor-online: true

msg-declare: "&f[&aTowny&6Wars&f] &b%s &cdeclared war on &6%j!"
msg-end: "&f[&aTowny&6Wars&f] &b%s &cwin war on &6%j!"
msg-notown: "&f[&aTowny&6Wars&f] &cYou don't belong to a town!"
msg-wrtown: "&f[&aTowny&6Wars&f] &cWrong town!"
msg-ntown: "&f[&aTowny&6Wars&f] &cNeutral town can't be in war!"
msg-war: "&f[&aTowny&6Wars&f] &bCurrent wars: "
msg-nlist: "&f[&aTowny&6Wars&f] &aNeutral towns: "
msg-non: "&f[&aTowny&6Wars&f] &bNow town &6%s&b is neutral"
msg-noff: "&f[&aTowny&6Wars&f] &bNow town &6%s&b is no longer neutral!"
msg-listde: "&f[&aTowny&6Wars&f] &cNo neutral towns!"
msg-warde: "&f[&aTowny&6Wars&f] &cNo active wars!"
msg-tde: "&f[&aTowny&6Wars&f] &aTown doesn't exists!"
msg-online: "&f[&aTowny&6Wars&f] &aMayor must be online!"
msg-win: "&f[&aTowny&6Wars&f] &aWin! &bYour town win the war!"
msg-lose: "&f[&aTowny&6Wars&f] &cLose! &bYour town lose the war!"
msg-points: "&f[&aTowny&6Wars&f] &bPoints: &6%s &bvs &6%k"
msg-money: "&f[&aTowny&6Wars&f] You must have %s to do that!"

msg-sendreq: "&f[&aTowny&6Wars&f] &aYou successfully send request to join a war"
msg-sendreqend: "&f[&aTowny&6Wars&f] &aYou successfully send request to end a war"
msg-sended: "&f[&aTowny&6Wars&f] &cThe request has already been sent"
msg-cancel: "&f[&aTowny&6Wars&f] &6Your request was successfully canceled"
msg-noreq: "&f[&aTowny&6Wars&f] &cYou didn't send any requests"
msg-mayoroffline: "&cMayor is offline!"

msg-accept: "&f[&aTowny&6Wars&f] &aYou successfully accepted request to join your war!"
msg-noreqrec: "&f[&aTowny&6Wars&f] &cYou didn't receive request!"
msg-inwar: "&f[&aTowny&6Wars&f] &cThis town already in war!"
msg-ninwar: "&f[&aTowny&6Wars&f] &cYou must be not in war!"

msg-req: "&f[&aTowny&6Wars&f] &bTown %s want to be your ally. &6Type &b/twar invite %s&6 to accept request."
msg-reqend: "&f[&aTowny&6Wars&f] &bTown %s want to end war. &6Type &b/twar end&6 to accept request."
msg-ended: "&f[&aTowny&6Wars&f] &bThe war is over. Peace was made."

#Other
no-args: "&f[&aTowny&6Wars&f] &cWrong arguments. Try to use &b/twar help"
no-perm: "&f[&aTowny&6Wars&f] &cYou do not have permission."

#Traditionnaly features
trfeatures: true
bye-bye: "&6Пока-пока, &b%s.&6 F."
# Town cancel pre-delete event not available in Towny on 1.12.2
block-town-delete: true

#Help
ht: "&bHelp"
ht1: "&b/twar declare <town>&f- &6declare &fwar to town"
ht2: "&b/twar n &f- toggle &6neutrality &fof your town"
ht3: "&b/twar st &f- see &6active wars &flist with points"
ht4: "&b/twar nlist &f- see &6neutral &ftowns list"
ht5: "&b/twar reload &f- &6reload &fall config files"
ht6: "&b/twar joinwar <town> &f- &6join existing war"
ht7: "&b/twar canceljw &f- &6cancel join war request"
ht8: "&b/twar st <town> &f- see &6information &fabout war"
ht9: "&b/twar invite <town> &f- accept &6join-war request"

config-ver: 1.4